name: 02-Hello world-OnPush

on: push

jobs:
  mybuildpush:
    runs-on:  ubuntu-latest
    steps:
      - name: Print a greeting
        run:  echo "Hello Github Actions! :)"
      - name: Print multiline greeting
        run: |
         echo  "This step runs multi line"
         echo  "This step runs on $RUNNER_OS"
         echo  "Current repository is $GITHUB_REPOSITORY"
